gripper:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  mode: gd_c
  dpos: 0.0001
  drot: 0.0001
  
ARM_1:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  mode: gd_c
  dpos: 0.0001
  drot: 0.0001

ARM_2:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  mode: gd_c
  dpos: 0.0001
  drot: 0.0001

ARM_3:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  mode: gd_c
  dpos: 0.0001
  drot: 0.0001

ARM_4:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  mode: gd_c
  dpos: 0.0001
  drot: 0.0001

MOBILE_BASE:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  mode: gd_c
  dpos: 0.0001
  drot: 0.0001

# WHOLE_BODY:
#   kinematics_solver: bio_ik/BioIKKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   kinematics_solver_attempts: 3
#   mode: gd_c
#   dpos: 0.0001
#   drot: 0.0001

