# Default initial positions for ivr's ros2_control fake system

initial_positions:
  ARM1_JOINT1: 0
  ARM1_JOINT2: 0
  ARM1_JOINT3: 0
  ARM1_JOINT4: 0
  ARM1_JOINT5: 0
  ARM1_JOINT6: 0
  ARM1_JOINT7: 0
  ARM2_JOINT1: 0
  ARM2_JOINT2: 0
  ARM2_JOINT3: 0
  ARM2_JOINT4: 0
  ARM2_JOINT5: 0
  ARM2_JOINT6: 0
  ARM2_JOINT7: 0
  ARM3_JOINT1: 0
  ARM3_JOINT2: 0
  ARM3_JOINT3: 0
  ARM3_JOINT4: 0
  ARM3_JOINT5: 0
  ARM3_JOINT6: 0
  ARM3_JOINT7: 0
  ARM4_JOINT1: 0
  ARM4_JOINT2: 0
  ARM4_JOINT3: 0
  ARM4_JOINT4: 0
  ARM4_JOINT5: 0
  ARM4_JOINT6: 0
  ARM4_JOINT7: 0
  BODY_JOINT_X: 0
  BODY_JOINT_Y: 0
  BODY_JOINT_Z: 0
  BODY_JOINT_YAW: 0
  BODY_JOINT_PITCH: 0
  BODY_JOINT_ROLL: 0
  ARM1_GRIPPER: 0
  