# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  ARM1_GRIPPER:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM1_JOINT1:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM1_JOINT2:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM1_JOINT3:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM1_JOINT4:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM1_JOINT5:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM1_JOINT6:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM1_JOINT7:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM2_JOINT1:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM2_JOINT2:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM2_JOINT3:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM2_JOINT4:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM2_JOINT5:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM2_JOINT6:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM2_JOINT7:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM3_JOINT1:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM3_JOINT2:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM3_JOINT3:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM3_JOINT4:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM3_JOINT5:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM3_JOINT6:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM3_JOINT7:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM4_JOINT1:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM4_JOINT2:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM4_JOINT3:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM4_JOINT4:
    has_velocity_limits: true
    max_velocity: 2.4543692606170255
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM4_JOINT5:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM4_JOINT6:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  ARM4_JOINT7:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  BODY_JOINT_X:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  BODY_JOINT_Y:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  BODY_JOINT_Z:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  BODY_JOINT_YAW:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  BODY_JOINT_PITCH:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0
  BODY_JOINT_ROLL:
    has_velocity_limits: true
    max_velocity: 3.2724923474893677
    has_acceleration_limits: true
    max_acceleration: 10.0