# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - MOBILE_BASE_controller
    - ARM_1_controller
    - ARM_2_controller
    - ARM_3_controller
    - ARM_4_controller
    - gripper_controller

  MOBILE_BASE_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - BODY_JOINT_X
      - BODY_JOINT_Y
      - BODY_JOINT_Z
      - BODY_JOINT_YAW
      - BODY_JOINT_PITCH
      - BODY_JOINT_ROLL

  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - ARM1_GRIPPER

  ARM_1_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - ARM1_JOINT1
      - ARM1_JOINT2
      - ARM1_JOINT3
      - ARM1_JOINT4
      - ARM1_JOINT5
      - ARM1_JOINT6
      - ARM1_JOINT7

  ARM_2_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - ARM2_JOINT1
      - ARM2_JOINT2
      - ARM2_JOINT3
      - ARM2_JOINT4
      - ARM2_JOINT5
      - ARM2_JOINT6
      - ARM2_JOINT7

  ARM_3_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - ARM3_JOINT1
      - ARM3_JOINT2
      - ARM3_JOINT3
      - ARM3_JOINT4
      - ARM3_JOINT5
      - ARM3_JOINT6
      - ARM3_JOINT7

  ARM_4_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - ARM4_JOINT1
      - ARM4_JOINT2
      - ARM4_JOINT3
      - ARM4_JOINT4
      - ARM4_JOINT5
      - ARM4_JOINT6
      - ARM4_JOINT7