# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    MOBILE_BASE_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    ARM_1_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    ARM_2_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    ARM_3_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    ARM_4_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

MOBILE_BASE_controller:
  ros__parameters:
    joints:
      - BODY_JOINT_X
      - BODY_JOINT_Y
      - BODY_JOINT_Z
      - BODY_JOINT_YAW
      - BODY_JOINT_PITCH
      - BODY_JOINT_ROLL
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joints:
      - ARM1_GRIPPER
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

ARM_1_controller:
  ros__parameters:
    joints:
      - ARM1_JOINT1
      - ARM1_JOINT2
      - ARM1_JOINT3
      - ARM1_JOINT4
      - ARM1_JOINT5
      - ARM1_JOINT6
      - ARM1_JOINT7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

ARM_2_controller:
  ros__parameters:
    joints:
      - ARM2_JOINT1
      - ARM2_JOINT2
      - ARM2_JOINT3
      - ARM2_JOINT4
      - ARM2_JOINT5
      - ARM2_JOINT6
      - ARM2_JOINT7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

ARM_3_controller:
  ros__parameters:
    joints:
      - ARM3_JOINT1
      - ARM3_JOINT2
      - ARM3_JOINT3
      - ARM3_JOINT4
      - ARM3_JOINT5
      - ARM3_JOINT6
      - ARM3_JOINT7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

ARM_4_controller:
  ros__parameters:
    joints:
      - ARM4_JOINT1
      - ARM4_JOINT2
      - ARM4_JOINT3
      - ARM4_JOINT4
      - ARM4_JOINT5
      - ARM4_JOINT6
      - ARM4_JOINT7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity